const FIREBALL_DROP_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_wrapperAddress", type: "address", internalType: "address" },
      { name: "_linkAddress", type: "address", internalType: "address" },
      { name: "_callbackGasLimit", type: "uint32", internalType: "uint32" },
      { name: "_platformFeePercent", type: "uint16", internalType: "uint16" },
      { name: "_feeReceiver", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "fallback", stateMutability: "payable" },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "MAX_NUM_WORDS",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "REQUEST_CONFIRMATIONS",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "callbackGasLimit",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelDrop",
    inputs: [{ name: "dropId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRefund",
    inputs: [{ name: "dropId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimedRefunds",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createDrop",
    inputs: [
      { name: "entryFee", type: "uint256", internalType: "uint256" },
      { name: "rewardAmount", type: "uint256", internalType: "uint256" },
      { name: "rewardToken", type: "address", internalType: "address" },
      {
        name: "rewardType",
        type: "uint8",
        internalType: "enum FireballDrop.RewardType",
      },
      { name: "rewardTokenIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "maxParticipants", type: "uint256", internalType: "uint256" },
      { name: "isPaidEntry", type: "bool", internalType: "bool" },
      { name: "isManualSelection", type: "bool", internalType: "bool" },
      { name: "numWinners", type: "uint32", internalType: "uint32" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "dropCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "drops",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "dropId", type: "uint256", internalType: "uint256" },
      { name: "host", type: "address", internalType: "address" },
      { name: "sponsor", type: "address", internalType: "address" },
      { name: "entryFee", type: "uint256", internalType: "uint256" },
      { name: "rewardAmount", type: "uint256", internalType: "uint256" },
      { name: "rewardToken", type: "address", internalType: "address" },
      {
        name: "rewardType",
        type: "uint8",
        internalType: "enum FireballDrop.RewardType",
      },
      { name: "maxParticipants", type: "uint256", internalType: "uint256" },
      { name: "currentParticipants", type: "uint256", internalType: "uint256" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "isCompleted", type: "bool", internalType: "bool" },
      { name: "isPaidEntry", type: "bool", internalType: "bool" },
      { name: "isManualSelection", type: "bool", internalType: "bool" },
      { name: "isSponsored", type: "bool", internalType: "bool" },
      { name: "numWinners", type: "uint32", internalType: "uint32" },
      { name: "fundingDeadline", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeReceiver",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundSponsoredGame",
    inputs: [{ name: "dropId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDropInfo",
    inputs: [{ name: "dropId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "host", type: "address", internalType: "address" },
      { name: "sponsor", type: "address", internalType: "address" },
      { name: "entryFee", type: "uint256", internalType: "uint256" },
      { name: "rewardAmount", type: "uint256", internalType: "uint256" },
      { name: "rewardToken", type: "address", internalType: "address" },
      {
        name: "rewardType",
        type: "uint8",
        internalType: "enum FireballDrop.RewardType",
      },
      { name: "rewardTokenIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "maxParticipants", type: "uint256", internalType: "uint256" },
      { name: "currentParticipants", type: "uint256", internalType: "uint256" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "isCompleted", type: "bool", internalType: "bool" },
      { name: "isPaidEntry", type: "bool", internalType: "bool" },
      { name: "isManualSelection", type: "bool", internalType: "bool" },
      { name: "isSponsored", type: "bool", internalType: "bool" },
      { name: "numWinners", type: "uint32", internalType: "uint32" },
      { name: "fundingDeadline", type: "uint256", internalType: "uint256" },
      { name: "winners", type: "address[]", internalType: "address[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDropParticipants",
    inputs: [{ name: "dropId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "addresses", type: "address[]", internalType: "address[]" },
      { name: "names", type: "string[]", internalType: "string[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDropVrfRequests",
    inputs: [{ name: "dropId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "requestIds", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLinkToken",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract LinkTokenInterface",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUnfundedSponsoredDrops",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVrfRequestDetails",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "dropId", type: "uint256", internalType: "uint256" },
      { name: "isFulfilled", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasJoinedDrop",
    inputs: [
      { name: "dropId", type: "uint256", internalType: "uint256" },
      { name: "participant", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "hasJoined", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "i_vrfV2PlusWrapper",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IVRFV2PlusWrapper" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "joinDrop",
    inputs: [
      { name: "dropId", type: "uint256", internalType: "uint256" },
      { name: "name", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "linkAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "platformFeePercent",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rawFulfillRandomWords",
    inputs: [
      { name: "_requestId", type: "uint256", internalType: "uint256" },
      { name: "_randomWords", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "selectWinnersManually",
    inputs: [{ name: "dropId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sponsorGame",
    inputs: [
      { name: "rewardAmount", type: "uint256", internalType: "uint256" },
      { name: "rewardToken", type: "address", internalType: "address" },
      {
        name: "rewardType",
        type: "uint8",
        internalType: "enum FireballDrop.RewardType",
      },
      { name: "rewardTokenIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "maxParticipants", type: "uint256", internalType: "uint256" },
      { name: "isManualSelection", type: "bool", internalType: "bool" },
      { name: "numWinners", type: "uint32", internalType: "uint32" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePlatformFee",
    inputs: [{ name: "newFeePercent", type: "uint16", internalType: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawLink",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawNative",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "DropCancelled",
    inputs: [
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "host", type: "address", indexed: true, internalType: "address" },
      {
        name: "isPaidEntry",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "isSponsored",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "refundedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DropCreated",
    inputs: [
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "host", type: "address", indexed: true, internalType: "address" },
      {
        name: "entryFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "rewardAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "rewardToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "rewardType",
        type: "uint8",
        indexed: false,
        internalType: "enum FireballDrop.RewardType",
      },
      {
        name: "rewardTokenIds",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "maxParticipants",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "isPaidEntry",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "isManualSelection",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "numWinners",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameFunded",
    inputs: [
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "sponsor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "rewardToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "rewardType",
        type: "uint8",
        indexed: false,
        internalType: "enum FireballDrop.RewardType",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameSponsored",
    inputs: [
      {
        name: "gameId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sponsor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "rewardAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "rewardToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "rewardType",
        type: "uint8",
        indexed: false,
        internalType: "enum FireballDrop.RewardType",
      },
      {
        name: "rewardTokenIds",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "maxParticipants",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "isManualSelection",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "numWinners",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ParticipantJoined",
    inputs: [
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "participant",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "name", type: "string", indexed: false, internalType: "string" },
      {
        name: "currentParticipants",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxParticipants",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlatformFeeUpdated",
    inputs: [
      {
        name: "newFeePercent",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RefundClaimed",
    inputs: [
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "participant",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestFulfilled",
    inputs: [
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "randomWords",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "payment",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestSent",
    inputs: [
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "numWinners",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      {
        name: "isManualSelection",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WinnersSelected",
    inputs: [
      {
        name: "dropId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "winners",
        type: "address[]",
        indexed: false,
        internalType: "address[]",
      },
      {
        name: "prizeAmounts",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "platformFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "OnlyVRFWrapperCanFulfill",
    inputs: [
      { name: "have", type: "address", internalType: "address" },
      { name: "want", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
];

module.exports = { FIREBALL_DROP_ABI };
